spring:
  server:
    port: 8080
  datasource:
    url: jdbc:mysql://localhost:3306/sparrow?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10
    username: root
    password: root


